name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install libcurses-dev
      run: sudo apt-get update && sudo apt-get install -y libncurses-dev

    - name: Configure
      run: cmake .
    - name: Build
      run: cmake --build . -j4 --target ALL_BUILD --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-latest
        path: |
          ./sf*
          ./*.yaml
          lang/

  build_macos:
    runs-on: macos-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure
      run: cmake . -DCURSES_INCLUDE_PATH=/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include
    - name: Build
      run: cmake --build . -j4 --target ALL_BUILD --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-latest
        path: |
          ./sf*
          ./*.yaml
          lang/

  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure
      run: cmake .
    - name: Build
      run: cmake --build . -j4 --target ALL_BUILD --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-latest
        path: |
          ./*.exe
          ./*.yaml
          lang/
